"""Documented self-check noise bounds (FR-003, SC-001).

The self-check (``dehip self-check``) scores a human reference set against itself
by splitting it in half. Because both halves are human text from one
distribution, the metrics must come back near their identity values: MMD near
zero, token-L2 near zero, and a JMQ win-rate near 50%. "Near" needs a number,
and an invented number would defeat the purpose of the check -- too loose and a
metric bug slips through, too tight and clean runs fail. So the MMD and token-L2
bounds are DERIVED EMPIRICALLY from repeated seeded half-splits, set just above
the largest noise value observed, with margin.

Two bound sets live here:

- :data:`STUB_INSTRUMENT_BOUNDS` -- derived and in force today. The real
  embedder (``nvidia/llama-embed-nemotron-8b``) and Qwen3 tokenizer need model
  downloads and a GPU/network, so they cannot run in CI or the test suite. These
  bounds are derived using the SAME deterministic stub embedder / stub tokenizer
  the integration tests use, and they are what ``dehip self-check`` asserts
  against until issue #16 fills in the real-instrument slot.
- :data:`REAL_INSTRUMENT_BOUNDS` -- the clearly-marked slot for issue #16. It is
  ``None`` today; #16's real smoke run over the FineWeb smoke corpus (50 pairs)
  with the production embedder and tokenizer will re-derive the bounds and fill
  it in. Until then the CLI uses the stub bounds and the JMQ win-rate window
  (45-55%, SC-001), which is instrument-independent.

Derivation provenance for :data:`STUB_INSTRUMENT_BOUNDS`
-------------------------------------------------------
- **Date:** 2026-08-05.
- **Instruments:** the deterministic stub embedder (hash-seeded 4-D
  standard-normal, ``embedder_id="stub-embedder"``) and stub tokenizer
  (whitespace split, ``tokenizer_id="stub-tokenizer"``) -- byte-for-byte the
  stubs in ``tests/integration/test_self_check.py`` and ``scripts/derive_bounds``.
- **Corpus:** ``stub-smoke-50`` -- a 50-pair (smoke-tier-sized) fixed human-like
  prose corpus generated by ``scripts/derive_bounds.py``
  (``_build_stub_smoke_corpus``), byte-identical to the corpus the SC-001
  verification test builds (``_write_reference``). Deterministic, so the
  derivation reproduces exactly.
- **Method:** for each seed in ``DERIVATION_SEEDS`` below (0..23), run the REAL
  self-check path (``dehip.self_check.run_self_check`` -> ``dehip.report.score``,
  MMD + token-L2, ``--skip-jmq``) over a fresh seeded half-split (25 vs 25 pairs)
  and record the scored MMD^2 and token-L2 distance.
- **Observed (24 seeds 0..23):**
    - MMD^2 ranged ``-0.02331335 .. +0.02948646`` (abs-max ``0.02948646``); the
      unbiased estimator is not constrained non-negative for same-distribution
      samples, so it straddles zero.
    - token-L2 ranged ``0.02505222 .. 0.04379749``.
- **Contrast (justifies the margin):** the same instruments on a genuine
  distribution shift (a mean-shifted embedding set / a disjoint-vocabulary text
  set) score MMD^2 ~= 0.40 and token-L2 ~= 0.57 -- roughly 14x and 13x the noise
  ceiling. The bounds below sit well between the noise ceiling and this
  regression floor, so real noise passes while a metric regression fails loudly.
- **Bounds chosen:**
    - ``mmd_max = 0.10`` -- above the observed positive max (0.0295) and abs-max
      (0.0295) with ~3.4x headroom, far below the ~0.40 regression signal. MMD is
      checked as an upper bound: a same-distribution split sits at/below ~0 and
      passes; a regression pushes MMD up and trips it.
    - ``token_l2_max = 0.10`` -- ~2.3x the observed max (0.0438), far below the
      ~0.57 regression signal.

Re-derive with: ``uv run python scripts/derive_bounds.py``.

JMQ win-rate bounds are NOT instrument-derived: SC-001 fixes them at 45-55%
(a fair judge on two same-distribution halves wins ~half the comparisons). They
apply to both stub and real instruments unchanged.
"""

from __future__ import annotations

from dataclasses import dataclass

__all__ = [
    "StubInstrumentBounds",
    "DERIVATION_SEEDS",
    "DERIVATION_CORPUS_ID",
    "STUB_INSTRUMENT_BOUNDS",
    "REAL_INSTRUMENT_BOUNDS",
]

# The seeds the stub-instrument bounds were derived over (scripts/derive_bounds).
DERIVATION_SEEDS: tuple[int, ...] = (0, 1, 2, 3, 4, 5, 6, 7)

# The fixed stub smoke corpus id the derivation ran against (50 pairs).
DERIVATION_CORPUS_ID = "stub-smoke-50"


@dataclass(frozen=True)
class StubInstrumentBounds:
    """Noise bounds the self-check asserts against.

    ``mmd_max`` and ``token_l2_max`` are upper limits: a same-distribution split
    scores at or below them, a metric regression exceeds them. ``jmq_win_rate_min``
    and ``jmq_win_rate_max`` bracket the JMQ model win-rate window (SC-001's
    45-55%). All four are inclusive limits.

    The name says "stub" because the in-force values were derived with the stub
    instruments (see the module docstring); the class is reused for the real
    instrument slot once issue #16 derives those. The MMD/token-L2 numbers are
    instrument-specific; the JMQ window is not.
    """

    mmd_max: float
    token_l2_max: float
    jmq_win_rate_min: float = 0.45
    jmq_win_rate_max: float = 0.55

    @classmethod
    def documented(cls) -> StubInstrumentBounds:
        """Return the bounds currently in force (stub instruments today).

        Once issue #16 fills in :data:`REAL_INSTRUMENT_BOUNDS`, that slot becomes
        the in-force set for real-instrument runs; until then the stub bounds are
        authoritative and this returns them.
        """
        return REAL_INSTRUMENT_BOUNDS or STUB_INSTRUMENT_BOUNDS


# In force today. Derived per the module docstring (2026-08-05, stub instruments,
# stub-smoke-50 corpus, seeds 0..7). See scripts/derive_bounds.py to re-derive.
STUB_INSTRUMENT_BOUNDS = StubInstrumentBounds(
    mmd_max=0.10,
    token_l2_max=0.10,
    jmq_win_rate_min=0.45,
    jmq_win_rate_max=0.55,
)

# --- Issue #16 slot: real-instrument bounds (FILL IN LATER) ------------------
# A real smoke run over the FineWeb smoke corpus (50 pairs) with the production
# embedder (nvidia/llama-embed-nemotron-8b) and Qwen3 tokenizer will re-derive
# the MMD and token-L2 noise bounds and replace this None with a
# StubInstrumentBounds(...) carrying its own dated provenance (real embedder id,
# real tokenizer id, the FineWeb smoke corpus manifest hash, the seeds used, the
# observed ranges). Until #16 lands, this stays None and StubInstrumentBounds
# .documented() falls back to STUB_INSTRUMENT_BOUNDS. Do NOT invent these numbers;
# they must come from a real run.
REAL_INSTRUMENT_BOUNDS: StubInstrumentBounds | None = None
